#!/bin/bash
#$ -S /bin/bash
#$ -cwd

#using NYU's HPC server

#goto the PARENT directory of the folder containing the rsem outputs

#Usage: gene_norm <sample 1 9 10 11> <replicate a or b>
#example: qsub -pe threaded 1 /ifs/home/asm523/tcga_pipe/gene_norm 1 a

sample=$1
rep=$2

#removes the uc0* lines
mv ${sample}${rep}/${sample}${rep}.rsem.genes.results \
    ${sample}${rep}/${sample}${rep}.orig.genes.results; \
    sed /^uc0/d ${sample}${rep}/${sample}${rep}.orig.genes.results > ${sample}${rep}/${sample}${rep}.rsem.genes.results

#quant norm of 2nd column in file
perl \
    /ifs/home/asm523/webshare.bioinf.unc.edu/public/mRNAseq_TCGA/quartile_norm.pl \
    -c 2 -q 75 -t 1000 \
    -o ${sample}${rep}/${sample}${rep}.rsem.genes.normalized_results \
    ${sample}${rep}/${sample}${rep}.rsem.genes.results


